accounts/urls.py
from django.urls import path
from unicodedata import name
from. import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns = [
    path('',views.Base.as_view(),name='base'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views,urls as acc_urls
from posts import urls as post_urls
from groups import urls as group_urls
from django.contrib.auth import urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include(acc_urls,namespace='accounts')),
    path('',views.Base.as_view()),
    path('accounts/',include('django.contrib.auth.urls')),
    path('Logout/',views.Logout.as_view(),name='logout'),
    path('groups/',include(group_urls,namespace='groups')),
    path('posts/', include(post_urls, namespace='posts')),
    path('about_us/',views.About.as_view(),name='about')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

posts/urls.py
from django.urls import path,re_path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(), name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(), name="single"),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete')
]

templates/Logout.html
{% extends 'base.html' %}
{% block content %}
    <h1>See you soon..</h1>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div style="background-color:darkslateblue" class="jumbotron">
  <div class="container">
    <h1 style="color: black">Some info</h1>
      <h2>Jumbotron</h2>
      <p>I had the same idea but when I tried that and it didn't work. The Jumbotron's background colour takes precedence over the bootstrap background colours. –
Mark Davies
 Jul 11, 2018 at 9:18
1
Yes this works. I created a class of .bg-jcol and added it to .jumbotron. Sometimes, you have to hold shift when resetting your web page to override the cached page. You will find the instructions in Bootstrap under the 'navbar' component. </p>
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '../static/css/master.css' %}">

</head>
<body>
<nav class="navbar mynav" id="navbar" role="navigation">
    <div class="container">
        <br>
        <ul class="nav navbar-nav navbar-left">
        <li><a href={% url 'accounts:base' %}>AITU Blog</a></li>
        <li><a href="https://moodle.astanait.edu.kz/">Moodle</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'posts:create' %}">Posts</a></li>
            <li><a href="{% url 'groups:create' %}">Create group</a></li>
            <li><a href="{% url 'accounts:logout' %}">logout</a></li>
{#                <li><a href="https://moodle.astanait.edu.kz/">Moodle</a></li>#}

            {% else %}
            <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
{#                <li><a href="https://moodle.astanait.edu.kz/">Moodle</a></li>#}
             <li><a href="{% url 'groups:all' %}">Groups</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
<canvas id="canvas"></canvas>
</body>
 <script src="{% static "../static/js/master.js" %}" type="text/javascript" ></script>
</html>

templates/hello.html
{% extends 'base.html' %}
{% block content %}
    <h1>Hello</h1>
{% endblock %}